# Generated by: cmestredelpino@itq.nl
#
# Generated on: 13/08/21
#

@{
  RootModule = 'pwshFunctions.psm1'
  ModuleVersion = '1.0.0'
  FunctionsToExport = "ImportVarsFromCSV", "Get-ESXIHost", "Get-VMCCredentials-From-TFState", "Get-DatastoreURL","CSV_to_JSON"
}
